networks:
  rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rodrigo
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      rabbitmq_net:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning", "--dir", "/data" ]
    volumes:
      - redis_data:/data
    networks:
      rabbitmq_net:
        ipv4_address: 172.30.0.11
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      rabbitmq_net:
        ipv4_address: 172.30.0.12
    restart: unless-stopped
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    volumes:
      - ./redis_commander_data:/home/app/.redis-commander
    networks:
      rabbitmq_net:
        ipv4_address: 172.30.0.13
    restart: unless-stopped

volumes:
  rabbitmq_data:
  redis_data:
  redisinsight_data:
  redis_commander_data:
